
stages:
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool: Advikpool
    # creates an environment if it doesn't exist
    environment: env15
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world